include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: false
    omit_local_variable_types: false
    prefer_final_fields: false
    annotate_overrides: false
    prefer_collection_literals: false
